// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYRGlDqt17sN2RTH3-HPFKeoOxW2GTXEY',
    appId: '1:47360168096:web:cc7ffd3114cf4adfa7b9c5',
    messagingSenderId: '47360168096',
    projectId: 'evenatus-db1c3',
    authDomain: 'evenatus-db1c3.firebaseapp.com',
    storageBucket: 'evenatus-db1c3.appspot.com',
    measurementId: 'G-4YMNMFHF2W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnBLtzua1KXA6j5fcVth4UD4-XDA7AqyU',
    appId: '1:47360168096:android:7d402c7bd145fcf5a7b9c5',
    messagingSenderId: '47360168096',
    projectId: 'evenatus-db1c3',
    storageBucket: 'evenatus-db1c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFxo2OUazvkZf_l_ySaTyej1_1TxRBazA',
    appId: '1:47360168096:ios:cc0a189d139d3cb6a7b9c5',
    messagingSenderId: '47360168096',
    projectId: 'evenatus-db1c3',
    storageBucket: 'evenatus-db1c3.appspot.com',
    iosBundleId: 'com.evenatus.projectBlackPanther',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFxo2OUazvkZf_l_ySaTyej1_1TxRBazA',
    appId: '1:47360168096:ios:cc0a189d139d3cb6a7b9c5',
    messagingSenderId: '47360168096',
    projectId: 'evenatus-db1c3',
    storageBucket: 'evenatus-db1c3.appspot.com',
    iosBundleId: 'com.evenatus.projectBlackPanther',
  );
}
